const Logos = {
    tvn: require('../images/channel_icons/tvn.png'),
    mega: require('../images/channel_icons/mega.png'),
    canal_13: require('../images/channel_icons/canal-13.png'),
    chilevision: require('../images/channel_icons/chilevision.png'),
    la_red: require('../images/channel_icons/la-red.png'),
    ucv_tv: require('../images/channel_icons/ucv-tv.png'),
    horas: require('../images/channel_icons/24-horas.png'),
    thirteen_c: require('../images/channel_icons/13-c.png'),
    star_channel: require('../images/channel_icons/star-channel.png'),
    tnt: require('../images/channel_icons/tnt.png'),
    hbo: require('../images/channel_icons/hbo.png'),
    sony: require('../images/channel_icons/sony.png'),
    axn: require('../images/channel_icons/axn.png'),
    warner_channel: require('../images/channel_icons/warner-channel.png'),
    a_e: require('../images/channel_icons/a-e.png'),
    universal_tv: require('../images/channel_icons/universal-channel.png'),
    fox_sports_3: require('../images/channel_icons/fox-sports-3.png'),
    lifetime: require('../images/channel_icons/lifetime.png'),
    discovery_science: require('../images/channel_icons/discovery-science.png'),
    discovery_channel: require('../images/channel_icons/discovery.png'),
    tyc_sports: require('../images/channel_icons/tyc-sports.png'),
    discovery: require('../images/channel_icons/discovery.png'),
    national_geographic: require('../images/channel_icons/national-geographic.png'),
    animal_planet: require('../images/channel_icons/animal-planet.png'),
    history: require('../images/channel_icons/history.png'),
    space: require('../images/channel_icons/space.png'),
    fx: require('../images/channel_icons/fx.png'),
    cdf_basico: require('../images/channel_icons/cdf-basico.png'),
    fox_sports_basico: require('../images/channel_icons/fox-sports-basico.png'),
    discovery_home_health: require('../images/channel_icons/discovery-home-health.png'),
    investigation_discovery: require('../images/channel_icons/discovery-id.png'),
    golden: require('../images/channel_icons/golden.png'),
    cinecanal: require('../images/channel_icons/cinecanal.png'),
    hbo_2: require('../images/channel_icons/hbo-2.png'),
    cinemax: require('../images/channel_icons/cinemax.png'),
    de_pelicula: require('../images/channel_icons/de-pelicula.png'),
    disney_channel: require('../images/channel_icons/disney-channel.png'),
    cartoon_network: require('../images/channel_icons/cartoon-network.png'),
    nick: require('../images/channel_icons/nickelodeon.png'),
    cnn_chile: require('../images/channel_icons/cnn-chile.png')
}

export default Logos