import Head from 'next/head'

// Global components
import Header from '../global-components/Header'
import Footer from '../global-components/Footer'

// Components
import Hero from '../components/Hero/Hero'
import GenericContent from '../components/GenericContent/GenericContent'
import Header_Mobile from '../global-components/Header_Mobile'


export default function CookiePolicy() {
  return (
    <div className={`main__wrapper`}>
      <Head>
        <title>Cookie policy - TV | Chile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Header_Mobile />

      <main className={`main`}>
        <Hero />
        <GenericContent
          title = "Cookie policy"
          description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        />
      </main>

      <Footer />

    </div>
  )
}
