import Head from 'next/head'
import Image from 'next/image'
import Header from '../global-components/Header'
import Footer from '../global-components/Footer'
import styles from '../styles/Home.module.scss'
import Hero from '../components/Hero'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tv | Chile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
          <Hero />
      </main>

      <Footer />

    </div>
  )
}
